version: '3.8'

services:
  frontend:
    image: node:18-alpine
    working_dir: /src
    volumes:
      - ./frontend:/src
      - /node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  backend:
    image: node:18-alpine
    working_dir: /src
    volumes:
      - ./backend:/src
      - /node_modules
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm run dev"
    environment:
      - DATABASE_URL=postgres://dev:stocks@postgres:5432/stock_app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: stocks
      POSTGRES_DB: stock_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
